### ISSUE TITLE
General rules

### ISSUE THREAD

**Issue by Rtut654** [drivendataorg/boem-belugas-runtime#24]
https://community.drivendata.org/t/increase-submissions-limit/7793/6?u=kirusha
@pjbull Sorry for asking here, but should it  be so illogical and unfair?

**Comment by Rtut654** [comment]
I may got it wrong from the rules page. If it is showing '1 week left' does it mean that I have 3 submissions before the end or it'll be according to the number of actual days?

**Comment by pjbull** [comment]
Answered in the forum where this discussion belongs. Closing here.
